#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config focused_border_color    '#FFD173'
bspc config presel_feedback_color   '#80BFFF'
bspc config normal_border_color     '#695380'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

for n in I II III IV V VI VII VIII IX X;
do
    bsp-layout set tall $n
done

$HOME/.local/bin/writeupdates.sh
picom &
nitrogen --restore
$HOME/.config/polybar/launch.sh

lxpolkit &
pkill -USR1 -x sxhkd

